//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAccess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAccess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Properties.ResourceAccess", typeof(ResourceAccess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, CountryName, CountryNameEN FROM Country.
        /// </summary>
        internal static string CountrySelect {
            get {
                return ResourceManager.GetString("CountrySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, EducationLevelName, EducationLevelNameEN FROM EducationLevel.
        /// </summary>
        internal static string EducationLevelSelect {
            get {
                return ResourceManager.GetString("EducationLevelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, CompanyName, CompanyNameEN FROM HealthInsurance.
        /// </summary>
        internal static string HealthInsuranceSelect {
            get {
                return ResourceManager.GetString("HealthInsuranceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, PensionType, PensionTypeEN FROM Retirement.
        /// </summary>
        internal static string RetirementSelect {
            get {
                return ResourceManager.GetString("RetirementSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, EmployeeState, EmployeeStateEN FROM State.
        /// </summary>
        internal static string StateSelect {
            get {
                return ResourceManager.GetString("StateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, Category, CategoryEN FROM WageCategory.
        /// </summary>
        internal static string WageCategorySelect {
            get {
                return ResourceManager.GetString("WageCategorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, JobExpire, JobExpireEN FROM WorkExpiration.
        /// </summary>
        internal static string WorkExpirationSelect {
            get {
                return ResourceManager.GetString("WorkExpirationSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, NameOfHoursPerWeek, NameOfHoursPerWeekEN FROM WorkHours.
        /// </summary>
        internal static string WorkHoursSelect {
            get {
                return ResourceManager.GetString("WorkHoursSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, Position, PositionEN FROM WorkPosition.
        /// </summary>
        internal static string WorkPositionSelect {
            get {
                return ResourceManager.GetString("WorkPositionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  ID, Type, TypeEN FROM WorkType.
        /// </summary>
        internal static string WorkTypeSelect {
            get {
                return ResourceManager.GetString("WorkTypeSelect", resourceCulture);
            }
        }
    }
}
