//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrosDotaznik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Questionnaire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questionnaire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KrosDotaznik.Resources.Questionnaire", typeof(Questionnaire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa trvalého bydliska.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obec/Mesto.
        /// </summary>
        internal static string lblAddressCity {
            get {
                return ResourceManager.GetString("lblAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        internal static string lblAddressPostalCode {
            get {
                return ResourceManager.GetString("lblAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica, číslo.
        /// </summary>
        internal static string lblAddressStreet {
            get {
                return ResourceManager.GetString("lblAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN na alarm.
        /// </summary>
        internal static string lblAlarmPin {
            get {
                return ResourceManager.GetString("lblAlarmPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo bankového účtu.
        /// </summary>
        internal static string lblBankAcc {
            get {
                return ResourceManager.GetString("lblBankAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum narodenia.
        /// </summary>
        internal static string lblBirthDate {
            get {
                return ResourceManager.GetString("lblBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum narodenia .
        /// </summary>
        internal static string lblChildBirthDate {
            get {
                return ResourceManager.GetString("lblChildBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno a priezvisko dieťaťa.
        /// </summary>
        internal static string lblChildFullName {
            get {
                return ResourceManager.GetString("lblChildFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚDAJE O DEŤOCH.
        /// </summary>
        internal static string lblChildInfo {
            get {
                return ResourceManager.GetString("lblChildInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Štátna príslušnosť.
        /// </summary>
        internal static string lblCitizenShip {
            get {
                return ResourceManager.GetString("lblCitizenShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTAKTY, ADRESY.
        /// </summary>
        internal static string lblContactAddress {
            get {
                return ResourceManager.GetString("lblContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súčasné štúdium.
        /// </summary>
        internal static string lblCurrentStudy {
            get {
                return ResourceManager.GetString("lblCurrentStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚDAJE O VZDELANÍ.
        /// </summary>
        internal static string lblEducation {
            get {
                return ResourceManager.GetString("lblEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úroveň vzdelanie.
        /// </summary>
        internal static string lblEducationLevel {
            get {
                return ResourceManager.GetString("lblEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamestnávateľ.
        /// </summary>
        internal static string lblEmployer {
            get {
                return ResourceManager.GetString("lblEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Len dohody: výnimka z dôchodkového poistenia.
        /// </summary>
        internal static string lblException {
            get {
                return ResourceManager.GetString("lblException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žena.
        /// </summary>
        internal static string lblFemale {
            get {
                return ResourceManager.GetString("lblFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pohlavie.
        /// </summary>
        internal static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZŤP.
        /// </summary>
        internal static string lblHandicap {
            get {
                return ResourceManager.GetString("lblHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miera postihnutia v %.
        /// </summary>
        internal static string lblHandicapInPercentage {
            get {
                return ResourceManager.GetString("lblHandicapInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravotná poisťovňa.
        /// </summary>
        internal static string lblHealthInsurance {
            get {
                return ResourceManager.GetString("lblHealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najvyššie dosiahnuté vzdelanie.
        /// </summary>
        internal static string lblHighestEducation {
            get {
                return ResourceManager.GetString("lblHighestEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        internal static string lblIBAN {
            get {
                return ResourceManager.GetString("lblIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo OP.
        /// </summary>
        internal static string lblIdentityCard {
            get {
                return ResourceManager.GetString("lblIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string lblJobFrom {
            get {
                return ResourceManager.GetString("lblJobFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string lblJobTo {
            get {
                return ResourceManager.GetString("lblJobTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné priezvisko.
        /// </summary>
        internal static string lblMaidenName {
            get {
                return ResourceManager.GetString("lblMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblMail {
            get {
                return ResourceManager.GetString("lblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbor.
        /// </summary>
        internal static string lblMajor {
            get {
                return ResourceManager.GetString("lblMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muž.
        /// </summary>
        internal static string lblMale {
            get {
                return ResourceManager.GetString("lblMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Národnosť.
        /// </summary>
        internal static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESLÁ A PRÍSTUPY.
        /// </summary>
        internal static string lblPassAndApproaches {
            get {
                return ResourceManager.GetString("lblPassAndApproaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo k výplatnej páske.
        /// </summary>
        internal static string lblPaycheckPass {
            get {
                return ResourceManager.GetString("lblPaycheckPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidný.
        /// </summary>
        internal static string lblPensionDisabled {
            get {
                return ResourceManager.GetString("lblPensionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starobný.
        /// </summary>
        internal static string lblPensionOldAge {
            get {
                return ResourceManager.GetString("lblPensionOldAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poberateľ dôchodku.
        /// </summary>
        internal static string lblPensionRecipient {
            get {
                return ResourceManager.GetString("lblPensionRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsluhový.
        /// </summary>
        internal static string lblPensionRetirement {
            get {
                return ResourceManager.GetString("lblPensionRetirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trvalé bydlisko.
        /// </summary>
        internal static string lblPermanentResidence {
            get {
                return ResourceManager.GetString("lblPermanentResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné číslo.
        /// </summary>
        internal static string lblPersonalId {
            get {
                return ResourceManager.GetString("lblPersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSOBNÉ ÚDAJE.
        /// </summary>
        internal static string lblPersonalInfo {
            get {
                return ResourceManager.GetString("lblPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefón.
        /// </summary>
        internal static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miesto narodenia.
        /// </summary>
        internal static string lblPlaceOfBirth {
            get {
                return ResourceManager.GetString("lblPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREDCHÁDZAJÚCE ZAMESTNANIE.
        /// </summary>
        internal static string lblPreviousJob {
            get {
                return ResourceManager.GetString("lblPreviousJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predošlé priezvisko.
        /// </summary>
        internal static string lblPreviousSurname {
            get {
                return ResourceManager.GetString("lblPreviousSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poberanie dôchodku od.
        /// </summary>
        internal static string lblRecievingAPensionFrom {
            get {
                return ResourceManager.GetString("lblRecievingAPensionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okres narodenia.
        /// </summary>
        internal static string lblRegionOfBirth {
            get {
                return ResourceManager.GetString("lblRegionOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Škola.
        /// </summary>
        internal static string lblSchool {
            get {
                return ResourceManager.GetString("lblSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zúčastnený v 2. piliery DSS.
        /// </summary>
        internal static string lblSecondPillar {
            get {
                return ResourceManager.GetString("lblSecondPillar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        internal static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priezvisko.
        /// </summary>
        internal static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplatňovanie daňového bonusu.
        /// </summary>
        internal static string lblTaxBonus {
            get {
                return ResourceManager.GetString("lblTaxBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prechodné bydlisko.
        /// </summary>
        internal static string lblTemporaryAddress {
            get {
                return ResourceManager.GetString("lblTemporaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prechodné bydlisko.
        /// </summary>
        internal static string lblTemporaryResidence {
            get {
                return ResourceManager.GetString("lblTemporaryResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozícia.
        /// </summary>
        internal static string lblWorkPosition {
            get {
                return ResourceManager.GetString("lblWorkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok ukončenia.
        /// </summary>
        internal static string lblYearOfEnd {
            get {
                return ResourceManager.GetString("lblYearOfEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áno.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
    }
}
